name: release

on:
  release:
    types: # This configuration does not affect the page_build event above
      - created
jobs:
  build:
    name: ${{ matrix.arch }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64
          - mips_24kc
          - aarch64_generic

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        uses: cielpy/gh-action-sdk@master
        env:
          ARCH: ${{ matrix.arch }}
          PACKAGES: clash
          CUSTOM_PKG_DIR: clash

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: bin/packages/${{ matrix.arch }}/base/clash*.ipk
